[project]
name = "statsforecast"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <bas@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64"]

[tasks]

[dependencies]
python = "~=3.9.0"
holidays= "<0.21"
jupyterlab= "*"
matplotlib= "*"
numba= ">=0.55.0"
numpy= ">=1.21.6"
pandas= ">=1.3.5"

[python-dependencies]
prophet = ">0"
pyarrow = ">0"
scipy = ">=1.7.3"
statsmodels = ">=0.13.2"
tabulate = ">0"
plotly = ">0"
utilsforecast = ">=0.0.5"