[package]
name = "pixi"
version = "0.15.1"
description = "A package management and workflow tool"
edition = "2021"
authors = ["pixi contributors <hi@prefix.dev>"]
homepage = "https://github.com/prefix-dev/pixi"
repository = "https://github.com/prefix-dev/pixi"
license = "BSD-3-Clause"
readme = "README.md"

[features]
default = ["native-tls"]
tokio-console-subscriber = ["tokio/tracing", "dep:console-subscriber"]
native-tls = [
    "reqwest/native-tls",
    "rattler_repodata_gateway/native-tls",
    "rattler/native-tls",
]
rustls-tls = [
    "reqwest/rustls-tls",
    "reqwest/rustls-tls-native-roots",
    "rattler_repodata_gateway/rustls-tls",
    "rattler/rustls-tls",
]
slow_integration_tests = []

# IMPORTANT: Don't change the astral-sh/uv dependency versions here do it in the patch section
# And if you add a uv dependency add it to the patch section please
[dependencies]
assert_matches = "1.5.0"
async-once-cell = "0.5.3"
async-recursion = "1.0.5"
cfg-if = "1.0.0"
chrono = "0.4.33"
clap = { version = "4.5.0", default-features = false, features = [
    "derive",
    "usage",
    "wrap_help",
    "std",
    "color",
    "error-context",
    "env",
] }
clap-verbosity-flag = "2.1.2"
clap_complete = "4.5.0"
console = { version = "0.15.8", features = ["windows-console-colors"] }

console-subscriber = { version = "0.2.0", optional = true }
deno_task_shell = "0.14.4"
dialoguer = "0.11.0"
dirs = "5.0.1"
distribution-filename = { git = "https://github.com/astral-sh/uv" }
distribution-types = { git = "https://github.com/astral-sh/uv" }
dunce = "1.0.4"
flate2 = "1.0.28"
futures = "0.3.30"
http-cache-reqwest = "0.13.0"
human_bytes = "0.4.3"
humantime = "2.1.0"
indexmap = { version = "2.2.2", features = ["serde"] }
indicatif = "0.17.7"
insta = { version = "1.34.0", features = ["yaml"] }
install-wheel-rs = { git = "https://github.com/astral-sh/uv" }
is_executable = "1.0.1"
itertools = "0.12.1"
lazy_static = "1.4.0"
miette = { version = "7.0.0", features = [
    "fancy",
    "supports-color",
    "supports-hyperlinks",
    "supports-unicode",
    "terminal_size",
    "textwrap",
] }
minijinja = { version = "1.0.12", features = ["builtins"] }
once_cell = "1.19.0"
pep440_rs = { git = "https://github.com/astral-sh/uv" }
pep508_rs = { git = "https://github.com/astral-sh/uv" }
platform-host = { git = "https://github.com/astral-sh/uv" }
platform-tags = { git = "https://github.com/astral-sh/uv" }
pypi-types = { git = "https://github.com/astral-sh/uv" }
rattler = { version = "0.18.0", default-features = false }
rattler_conda_types = { version = "0.18.0", default-features = false }
rattler_digest = { version = "0.18.0", default-features = false }
rattler_lock = { version = "0.18.0", default-features = false }
rattler_networking = { version = "0.18.0", default-features = false }
rattler_repodata_gateway = { version = "0.18.0", default-features = false, features = [
    "sparse",
] }
rattler_shell = { version = "0.18.0", default-features = false, features = [
    "sysinfo",
] }
rattler_solve = { version = "0.18.0", default-features = false, features = [
    "resolvo",
] }
rattler_virtual_packages = { version = "0.18.0", default-features = false }
regex = "1.10.3"
reqwest = { version = "0.11.24", default-features = false }
reqwest-middleware = "0.2.4"
reqwest-retry = "0.3.0"
self-replace = "1.3.7"
serde = "1.0.196"
serde-untagged = "0.1.5"
serde_json = "1.0.113"
serde_spanned = "0.6.5"
serde_with = { version = "3.6.1", features = ["indexmap"] }
serde_yaml = "0.9.31"
shlex = "1.3.0"
spdx = "0.10.3"
strsim = "0.10.0"
tabwriter = { version = "1.4.0", features = ["ansi_formatting"] }
tar = "0.4.40"
tempfile = "3.10.0"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tokio-util = "0.7.10"
toml_edit = { version = "0.21.1", features = ["serde"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"
uv-cache = { git = "https://github.com/astral-sh/uv" }
uv-client = { git = "https://github.com/astral-sh/uv" }
uv-dispatch = { git = "https://github.com/astral-sh/uv" }
uv-distribution = { git = "https://github.com/astral-sh/uv" }
uv-installer = { git = "https://github.com/astral-sh/uv" }
uv-interpreter = { git = "https://github.com/astral-sh/uv" }
uv-normalize = { git = "https://github.com/astral-sh/uv" }
uv-resolver = { git = "https://github.com/astral-sh/uv" }
uv-traits = { git = "https://github.com/astral-sh/uv" }

zip = { version = "0.6.6", default-features = false, features = [
    "deflate",
    "time",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27.1", default-features = false, features = [
    "fs",
    "signal",
    "term",
    "poll",
] }
libc = { version = "0.2.153", default-features = false }
signal-hook = "0.3.17"

[dev-dependencies]
rattler_digest = "0.18.0"
rstest = "0.18.2"
serde_json = "1.0.113"
serial_test = "2.0.0"
tokio = { version = "1.36.0", features = ["rt"] }
toml = "0.8.10"

[patch.crates-io]
# For pyproject-toml
# If you change this also change the versions in the the patch section for astral
pep440_rs = { git = "https://github.com/astral-sh/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
pep508_rs = { git = "https://github.com/astral-sh/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }

rattler = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_conda_types = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_digest = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_lock = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_networking = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_repodata_gateway = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_shell = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_solve = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
rattler_virtual_packages = { git = "https://github.com/baszalmstra/rattler", rev = "e18356d674913385eb2c4ebb5a3407a329907409" }
#deno_task_shell = { path = "../deno_task_shell" }#rattler = { path = "../rattler/crates/rattler" }#rattler_conda_types = { path = "../rattler/crates/rattler_conda_types" }#rattler_digest = { path = "../rattler/crates/rattler_digest" }
#rattler_networking = { path = "../rattler/crates/rattler_networking" }
#rattler_repodata_gateway = { path = "../rattler/crates/rattler_repodata_gateway" }
#rattler_shell = { path = "../rattler/crates/rattler_shell" }
#rattler_solve = { path = "../rattler/crates/rattler_solve" }
#rattler_virtual_packages = { path = "../rattler/crates/rattler_virtual_packages" }
#rattler_lock = { path = "../rattler/crates/rattler_lock" }
#rip = { package = "rattler_installs_packages", path = "../rip" }


# IMPORTANT: This is a temporary patch to use the uv crate from git
# until the crates are published change stuff here and not in the dependencies section
# ALSO change the pep440_rs and pep508_rs in the crates-io section, otherwise pyproject fails
[patch.'https://github.com/astral-sh/uv']
pep440_rs = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
pep508_rs = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-cache = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-client = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-dispatch = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-distribution = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-installer = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-interpreter = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-normalize = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-resolver = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
uv-traits = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
distribution-filename = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
distribution-types = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
install-wheel-rs = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
platform-host = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
platform-tags = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
pypi-types = { git = "https://github.com/tdejager/uv", rev = "0fbfa110139f9af1ef15f8e4665c6b7a5fc4a39f" }
