[project]
name = "pypi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = "~=3.11.0"
colorama = "0.4.6"

[python-dependencies]
flask = "~=3.0"
