[project]
name = "pypi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]

[dependencies]
python = "~=3.10.0"
numpy = "*"

[python-dependencies]
pyboy = "1.6.6"
tensorflow = "2.14.0"
flask = "3.0.0"
black = "~=23.10"
